### PR TITLE
Support both PDFBox v2 and v3 #148

### LINKED ISSUE #148: Doesn't work with PDFBox 3.0.0-alpha3
It return this error: java.lang.NoClassDefFoundError: Could not initialize class org.vandeseer.easytable.structure.Table.
The dependency is imported correctly in the pom file.

### PR DESCRIPTION
**Pull request by jsimomaa**
Uses reflection to determine PDFBox runtime environment version. Fixes #148

### CODE REVIEW

**Comment by mptardy** [comment]
@jsimomaa thanks a lot!
@vandeseer would be amazing to get this merged and released.

**Comment by vandeseer** [comment]
Hey @jsimomaa, thanks a lot for your pull request! I honestly haven't had a look into PDFBox 3.x.x yet – simply because I don't really need the easytable library myself anymore. 
I quickly tried to build the code with your changes, but I see that there are some more compile issues ...

**Comment by vandeseer** [comment]
I upgraded the `develop` branch to be compatible with PDFBox 3. You can download and build it for trying it out. I hope to release that in the next days using a new major version to indicate that bigger change.

**Comment by vandeseer** [comment]
@jsimomaa @mptardy I just released version 1.0.0 which supports PDFBox 3.x.x. 

Thanks for your PR @jsimomaa, but it's not that simple to support both versions with the same code base. Hence I decided to release a new one. However, your PR helped me to get started! :+1: :wink:
