### ISSUE TITLE
Doesn't work with PDFBox 3.0.0-alpha3

### ISSUE THREAD

**Issue by erirapce** [vandeseer/easytable#148]
It return this error: java.lang.NoClassDefFoundError: Could not initialize class org.vandeseer.easytable.structure.Table.
The dependency is imported correctly in the pom file.

**Comment by vandeseer** [comment]
Hey @erirapce,
Thanks for reporting. Didn't yet try it with the new version of PDFBox. Also not quite sure whether I will find enough time to support it ...

**Comment by erirapce** [comment]
Thanks for letting me know! :)

**Comment by henkka14** [comment]
Hello, I was also a bit interested in this as pdfbox has now officially released ```3.0.0``` in August.

I've been using the library a bit and had it working initially with ```3.0.0-RC1```. However, the official ```3.0.0``` version no longer works.

Table classes are imported fine, but they fail during compile time which is caused by removal of static font instances by pdfbox
https://github.com/apache/pdfbox/commit/2d529f94b17a3f23aa8b2f566bc33947a91c245a

The static initializers are used heavily currently in easytable, e.g. ```PDType1Font.TIMES_ROMAN```.

My current experience has been that the library could be fairly easily migrated to pdfbox ```v3`` while keeping support for ```v2``` with just the font changes, i.e.  ```PDType1Font.TIMES_ROMAN``` => ```new PDType1Font("Times-Roman")```

Is the library maintained still in any form or would it be possible to create pull requests for ```3.0.0``` support?

**Comment by adsafawqew** [comment]
problem is org.vandeseer.easytable.structure.Table line 19:

`private static final PDFont DEFAULT_FONT = PDType1Font.HELVETICA;`

should be replaced with:

`private static final PDFont DEFAULT_FONT = PDType1Font(FontName.HELVETICA);`

PDType1Font.HELVETICA doesn't exist anymore
tested with pdfbox v3.0.0

**Comment by henkka14** [comment]
Hey yes, I've been having this issue as well as the static initializers were removed

https://github.com/apache/pdfbox/commit/2d529f94b17a3f23aa8b2f566bc33947a91c245a

I was initially thinking this could work for both v2.x.x and v3.0.0, but it seems that ```Standard14Fonts.FontName``` is not yet available in v2.x.x, meaning that I've not found a way to support both pdfbox versions v2 and v3 simultaneously

https://github.com/apache/pdfbox/blob/2.0.29/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/font/Standard14Fonts.java
https://github.com/apache/pdfbox/blob/3.0.0/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/font/Standard14Fonts.java

(note I am not contributor to the repo, but I just use pdfbox actively)

**Comment by jsimomaa** [comment]
I created a PR that should fix this issue as PDFBox v3 has been released

**Comment by vandeseer** [comment]
Thanks for your PR once again @jsimomaa! :+1: 

I upgraded the `develop` branch. It supports PDFBox 3 now. A release will hopefully follow shortly. 
However, I decided to **only** support PDFBox 3 with the next release. Supporting both at the same time wouldn't make much sense given the complexity involved.

**Comment by vandeseer** [comment]
Just released version 1.0.0 which is basically the same code base but upgraded to support PDFBox 3 and Java 11.
